### ISSUE TITLE
Fixed .exe does not have valid entry point

### ISSUE THREAD

**Issue by brandonros** [Shhoya/MutantKiller#2]
![image](https://user-images.githubusercontent.com/8949910/168482803-c73b38e3-ef3f-4745-807b-2179e7edefcd.png)

VMProtect exe -> Scylla dump -> MutantKiller x64

**Comment by Shhoya** [comment]
Did you run it after fixing it using `MutantKiller`? Unfortunately, this tool is not an unpacker. It is just a tool to facilitate static analysis.
